runtime: python
env: flex
entrypoint: gunicorn -b:$PORT app:app

runtime_config:
  operating_system: ubuntu22
  python_version: 3

resources:
  cpu: 2
  memory_gb: 2.3
  disk_size_gb: 20
  volumes:
    - name: ramdisk1
      volume_type: tmpfs
      size_gb: 0.5
